package com.art.mapper;

import com.art.pojo.TContentCategory;
import com.art.pojo.TContentCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TContentCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content_category
     *
     * @mbggenerated Mon Oct 07 14:48:53 CST 2019
     */
    int countByExample(TContentCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content_category
     *
     * @mbggenerated Mon Oct 07 14:48:53 CST 2019
     */
    int deleteByExample(TContentCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content_category
     *
     * @mbggenerated Mon Oct 07 14:48:53 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content_category
     *
     * @mbggenerated Mon Oct 07 14:48:53 CST 2019
     */
    int insert(TContentCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content_category
     *
     * @mbggenerated Mon Oct 07 14:48:53 CST 2019
     */
    int insertSelective(TContentCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content_category
     *
     * @mbggenerated Mon Oct 07 14:48:53 CST 2019
     */
    List<TContentCategory> selectByExample(TContentCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content_category
     *
     * @mbggenerated Mon Oct 07 14:48:53 CST 2019
     */
    TContentCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content_category
     *
     * @mbggenerated Mon Oct 07 14:48:53 CST 2019
     */
    int updateByExampleSelective(@Param("record") TContentCategory record, @Param("example") TContentCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content_category
     *
     * @mbggenerated Mon Oct 07 14:48:53 CST 2019
     */
    int updateByExample(@Param("record") TContentCategory record, @Param("example") TContentCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content_category
     *
     * @mbggenerated Mon Oct 07 14:48:53 CST 2019
     */
    int updateByPrimaryKeySelective(TContentCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content_category
     *
     * @mbggenerated Mon Oct 07 14:48:53 CST 2019
     */
    int updateByPrimaryKey(TContentCategory record);
}