package com.art.mapper;

import com.art.pojo.TContent;
import com.art.pojo.TContentExample;
import com.art.pojo.TContentWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content
     *
     * @mbggenerated Mon Oct 07 14:48:53 CST 2019
     */
    int countByExample(TContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content
     *
     * @mbggenerated Mon Oct 07 14:48:53 CST 2019
     */
    int deleteByExample(TContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content
     *
     * @mbggenerated Mon Oct 07 14:48:53 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content
     *
     * @mbggenerated Mon Oct 07 14:48:53 CST 2019
     */
    int insert(TContentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content
     *
     * @mbggenerated Mon Oct 07 14:48:53 CST 2019
     */
    int insertSelective(TContentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content
     *
     * @mbggenerated Mon Oct 07 14:48:53 CST 2019
     */
    List<TContentWithBLOBs> selectByExampleWithBLOBs(TContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content
     *
     * @mbggenerated Mon Oct 07 14:48:53 CST 2019
     */
    List<TContent> selectByExample(TContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content
     *
     * @mbggenerated Mon Oct 07 14:48:53 CST 2019
     */
    TContentWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content
     *
     * @mbggenerated Mon Oct 07 14:48:53 CST 2019
     */
    int updateByExampleSelective(@Param("record") TContentWithBLOBs record, @Param("example") TContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content
     *
     * @mbggenerated Mon Oct 07 14:48:53 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") TContentWithBLOBs record, @Param("example") TContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content
     *
     * @mbggenerated Mon Oct 07 14:48:53 CST 2019
     */
    int updateByExample(@Param("record") TContent record, @Param("example") TContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content
     *
     * @mbggenerated Mon Oct 07 14:48:53 CST 2019
     */
    int updateByPrimaryKeySelective(TContentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content
     *
     * @mbggenerated Mon Oct 07 14:48:53 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(TContentWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_content
     *
     * @mbggenerated Mon Oct 07 14:48:53 CST 2019
     */
    int updateByPrimaryKey(TContent record);
}